### ISSUE TITLE
scraper.rb:4:in `<main>': iconv will be deprecated in the future, use String#encode instead.

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/greater_geelong#1]

**Comment by CloCkWeRX** [comment]
I really should have a closer look at this one

**Comment by mlandauer** [comment]
This was fixed in https://github.com/planningalerts-scrapers/greater_geelong/commit/520fcf262c77b59eaefa8680a3eaf38daa703944#diff-4fa627201df14a294b00abb2a0d97fb0 by upgrading ruby versions
