### ISSUE TITLE
Geelong Scraper is broken

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/greater_geelong#11]
Scraper seems to have stopped working 2 months ago. Someone reported a DA they want to be shared.
The Base URL at council does not seem to have changed. 
Error at https://morph.io/planningalerts-scrapers/greater_geelong as follows from last run: 
Using Australian proxy...
 /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `open'
 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:935:in `connect'
 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:915:in `start'
 	from /app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:655:in `start'
 	from /app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:595:in `connection_for'
 	from /app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:885:in `request'
 	from /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:280:in `fetch'
 	from /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.7/lib/mechanize.rb:464:in `get'
 	from scraper.rb:15:in `<main>'

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5fibp)

**Comment by mlandauer** [comment]
@katska issues for broken scrapers are automatically created in https://github.com/planningalerts-scrapers/issues/issues

Please add your comments to https://github.com/planningalerts-scrapers/issues/issues/730

I'll close this issue
